import { Nation } from './types';

export const INITIAL_NATIONS: Nation[] = [
  {
    id: 0,
    name: 'Velocity',
    emoji: '⚡',
    tagline: 'Speed / Real-Time Execution',
    color: '#00f0ff',
    meter: 1000,
    isEliminated: false,
    totalInfluenceSpent: 0,
    totalSupporters: 0,
  },
  {
    id: 1,
    name: 'Shadow',
    emoji: '🔒',
    tagline: 'Privacy / Confidentiality',
    color: '#a855f7',
    meter: 1000,
    isEliminated: false,
    totalInfluenceSpent: 0,
    totalSupporters: 0,
  },
  {
    id: 2,
    name: 'Vault',
    emoji: '🏛️',
    tagline: 'Ownership / Self-Custody',
    color: '#f59e0b',
    meter: 1000,
    isEliminated: false,
    totalInfluenceSpent: 0,
    totalSupporters: 0,
  },
  {
    id: 3,
    name: 'Flow',
    emoji: '💧',
    tagline: 'Liquidity / Capital Velocity',
    color: '#0ea5e9',
    meter: 1000,
    isEliminated: false,
    totalInfluenceSpent: 0,
    totalSupporters: 0,
  },
  {
    id: 4,
    name: 'Commons',
    emoji: '🌐',
    tagline: 'Decentralization / Open Access',
    color: '#10b981',
    meter: 1000,
    isEliminated: false,
    totalInfluenceSpent: 0,
    totalSupporters: 0,
  },
  {
    id: 5,
    name: 'Forge',
    emoji: '🔥',
    tagline: 'Permissionless Innovation',
    color: '#f97316',
    meter: 1000,
    isEliminated: false,
    totalInfluenceSpent: 0,
    totalSupporters: 0,
  },
  {
    id: 6,
    name: 'Council',
    emoji: '⚖️',
    tagline: 'Coordination / Governance',
    color: '#f43f5e',
    meter: 1000,
    isEliminated: false,
    totalInfluenceSpent: 0,
    totalSupporters: 0,
  },
  {
    id: 7,
    name: 'Genesis',
    emoji: '🪨',
    tagline: 'Settlement / Permanence',
    color: '#94a3b8',
    meter: 1000,
    isEliminated: false,
    totalInfluenceSpent: 0,
    totalSupporters: 0,
  },
];
